# This should contain tracker parameters

line_tracker_distance:
  default_v_des: 0.3
  default_a_des: 0.2
  epsilon: 0.1

line_tracker_min_jerk:
  default_v_des: 0.3
  default_a_des: 0.2
  default_yaw_v_des: 0.5
  default_yaw_a_des: 0.2

trajectory_tracker:
  max_vel_des: 0.3
  max_acc_des: 0.2
