# Reducing angular derivative
cable_length: 0.72 
attach_id: 1
rbgains:
  #pos: {x: 1.8, y: 1.8, z: 3.0}
  #vel: {x: 0.6, y: 0.6, z: 1.7}
  pos: {x: 7.1, y: 7.1, z: 11.9}
  vel: {x: 2.4, y: 2.4, z: 6.7}
  rot: {x: 1.5, y: 1.5, z: 1.0}
  ang: {x: 0.13, y: 0.13, z: 0.1}
  q: {x: 1.5, y: 1.5, z: 6.0}
  omega: {x: 0.13, y: 0.13, z: 0.1}
  #ki:  {x: 0.00, y: 0.001, z: 0.008}
  ki:  {x: 0.00, y: 0.004, z: 0.03}
  kib:  {x: 0.00, y: 0.004, z: 0.03}
Inertia:
  I: {Ix: 0.000601, Ixy: 0.0, Ixz: 0.0, Iyx: 0.0, Iy: 0.000589, Iyz: 0.0, Izx: 0.0, Izy: 0.0, Iz: 0.001076}
kf: 0.000000004179
kM_kf: 0.0095
arm_length: 0.07071067811
rhos:
  rho1: {x: 0.088, y: 0.0, z: 0.0}
  rho2: {x: -0.044, y: 0.0762, z: 0.0}
  rho3: {x: -0.044, y: -0.0762, z: 0.0}
corrections:
  kf: 0.0
  r: 0.0
  p: 0.0

